version: 'build #{build}'

environment:
  JAVA_HOME: C:\Program Files\Java\jdk1.8.0

build_script:
  - gradlew --no-daemon --info build run

artifacts:
  - path: build\konan\bin\mingw\Hello.exe
    name: build

deploy:
  provider: GitHub
  tag: $(APPVEYOR_REPO_TAG_NAME)
  description: 'v$(APPVEYOR_REPO_TAG_NAME)'
  artifact: build
  auth_token:
    secure: "2l/602m6FkqAB9TTIAkPX3Erfwg9jVTlf/Inmf2dWcbOrJJzK/WrCUIgY3B4ngly"
  draft: false
  prerelease: false
  on:
    appveyor_repo_tag: true
